// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/kaiyu.kong/kaiyu.kong/util/react-laziness-image/node_modules/dumi/theme-default/slots/NotFound/index.js';
