// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': {
      id: 'dumi-context-layout',
      path: '/',
      isLayout: true,
    },
    DocLayout: {
      id: 'DocLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true,
    },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'components/ProImage/index': {
      id: 'components/ProImage/index',
      path: 'components/pro-image',
      parentId: 'DocLayout',
      meta: { _atom_route: true },
    },
    'demo-render': {
      id: 'demo-render',
      path: '~demos/:id',
      parentId: 'dumi-context-layout',
      prerender: false,
    },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__404" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/.dumi/tmp-production/dumi/theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/docs/index.md'
          ),
      ),
      'components/ProImage/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "ProImage__index.md" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/src/ProImage/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
