// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demoIndex as dmi0 } from '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/docs/index.md?type=demo-index';
import {
  frontmatter as fm0,
  toc as t0,
} from '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/src/react-laziness-image/index.md?type=demo-index';
import {
  frontmatter as fm1,
  toc as t1,
} from '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/src/react-laziness-image/index.md?type=frontmatter';

export const filesMeta = {
  'docs/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/docs/index.md?type=text'
      ),
  },
  'components/react-laziness-image/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__react-laziness-image" */ '/Users/kaiyu.kong/kaiyu.kong/util/react-lazy-image/src/react-laziness-image/index.md?type=text'
      ),
  },
};

export { tabs as tabsMeta } from './tabs';
